### ISSUE TITLE
Главная картинка в Readme

### ISSUE THREAD

**Issue by kurnakovv** [Ulyanov-programmer/DefaultProject#1]
Вань, а ты можешь добавить картинку сайта в readme? Просто не всегда удобно заходить в github-page

**Comment by Ulyanov-programmer** [comment]
Думал над этим, и пожалуй, пришло время. 
Ожидай в понедельник скрины для всех ранее мной созданных сайтов в их readme.
Как думаешь, что мне выкладывать помимо самого верха страницы? Раздумываю так же над добавлением снимков мобильных версий.

**Comment by kurnakovv** [comment]
Да, я думаю 2х фоток будет достаточно (ПК и мобилка) остальное будет лишним.

**Comment by Ulyanov-programmer** [comment]
Были добавлены скриншоты сайтов (в т.ч мобильных версий) для всех актуальных репозиториев с вёрсткой.
Репозиторий же со стандартным проектом не нуждается в этом.

**Comment by kurnakovv** [comment]
Молодец!
