### ISSUE TITLE
Анимация при наведении

### ISSUE THREAD

**Issue by kurnakovv** [Ulyanov-programmer/DefaultProject#2]
Все круто, вот только когда мы навели на элемент, а потом отвели мышку - анимация не очень красивая, т.к надпись падает за границы элемента. Конечно возможно все было так и задумано, но было бы круто если бы ты это красивее обработал.

Если конечно не сложно :)

**Comment by Ulyanov-programmer** [comment]
Т.е не нравится сам эффект ухода элемента вниз? 
Есть идея - элемент будет как бы приближаться  к пользователю, из пикселя становясь на весь размер. Как на гифке ниже. При отведении мышки он снова сожмётся в пиксель. 
Но я желаю узнать твои идеи.
![5afda1e1a6a2c28e6048da5da2b79dc6](https://user-images.githubusercontent.com/66691708/129906458-4b6bb8d4-a805-463c-a803-57f9d58203d0.gif)

**Comment by kurnakovv** [comment]
Попробуй, посмотрим что получится))

**Comment by Ulyanov-programmer** [comment]
Несколькими последними коммитами была добавлена анимация, теперь при наведении окно плавно расширяется из низа картинки на весь размер, а при уведении курсора - плавно уменьшается, уходя _в закат_ к низу картинки.
