### ISSUE TITLE
Плавность в приближении

### ISSUE THREAD

**Issue by kurnakovv** [Ulyanov-programmer/DefaultProject#3]
А ты можешь сделать так что бы при скролле нижней панельки, она скроллилась плавно, а то сейчас там всего 4 вида приближения и это выглядит не очень круто : (

Я думаю js должен помочь.

**Comment by Ulyanov-programmer** [comment]
Я это реализовывал, с.м коммит 92de8485225a745ecf0a061f5132d4e0c68cbf16, он последний, где это работает. Откатись на него если хочешь.
Однако там немного по другому реализована сетка фотографий, они не прилипают к правому краю.
Что характерно, там действительно JS, и геморроя при разработке было больше. =]

ОБН: Я сделал [ветку](https://github.com/Ulyanov-programmer/PhotoManagement/tree/smoothSizing), в ней нет коммитов, где эта плавность убиралась. Не зря же я её делал, переключись на неё.

**Comment by kurnakovv** [comment]
А в чем проблема растянуть до конца экрана? Просто интересно

В данной ветке это намного круче выглядит, возможно код будет сложнее, но качество картинки по мне так важнее.

**Comment by Ulyanov-programmer** [comment]
Растянуть то не проблема, но:
1: Горизонтальное пространство между фото будет больше вертикального (не по макету);
2: Будут случатся вот такие казусы, когда элементы прижимаются к краям экрана: 
![image](https://user-images.githubusercontent.com/66691708/132939934-3221b56d-f8bb-408f-b269-dfc87a098227.png)

Проблема в специфике выравнивания элементов, их можно заставить выстраиваться по всей ширине альбома, но при этом казус выше исправить проблематично.
Можно их заставить выстраиваться равномерно по альбому, но не по макету:
![image](https://user-images.githubusercontent.com/66691708/132940498-073ccb2f-8547-47c1-a8d8-5f902a643a6d.png)


Возможно это решается каким-нибудь фреймворком, но я таких не знаю.

**Comment by kurnakovv** [comment]
А по макету как должно быть? Можешь скрин плез оставить (попробую найти решение) и + ты гриды используешь или flex? Или вообще что-то другое?

**Comment by Ulyanov-programmer** [comment]
Можно прямо [из гита посмотреть](https://github.com/Ulyanov-programmer/PhotoManagement/blob/master/Photo%20management.psd)!
В случае с тонкой регулировкой - флексы, менял размеры фото напрямую, через width. 
Обрати внимание, новые строки образуются, если размеров фото с отступами не хватает на линию, тогда те, что не вмещаются переезжают на новый ряд. (свойство `flex-wrap: wrap`)
В ином - гриды, менял к-во колонок (свойство `grid-template-columns:` и `grid-template:`), размеры вроде автоматом подстраиваются.

**Comment by kurnakovv** [comment]
Что-то не могу починять, ладно, пусть будет так. Я не супер тру верстальщик : (
